# Experiment 
model_name :  "FCN"
experiment_name :  "FCN-exp"
batch_size: 5
n_class: 10
lr: 0.001
epoch: 100
optimizer: 'Adam'
objective: 'CrossEntropyLoss'
verbose: False

# Dataset
data_path: 'data/tas500v1.1'
crop :  True
horizontal_flip :  True
vertical_flip :  True
color_jitter :  True
weighted: True



